spring.application.name=user-registration;
# MongoDB Connection String
spring.mongodb.uri=mongodb://localhost:27017/userdb
# Ithu nammude console-il queries kaanan sahayikkum
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
